import gzip
import logging
from collections.abc import AsyncIterator
from datetime import date, timedelta
from pathlib import Path

import httpx
import pytest
import respx

from app.collectors.base import CollectorContext, Cron, Cursor, RawRecord, definition_errors
from app.collectors.epss import (
    FEED_URL,
    EpssCollector,
    EpssScore,
    StoredScore,
    history_reason,
    parse_header,
)
from app.collectors.http import SourceHttpClient
from app.core.classification import Classification
from tests.collectors.fakes import FakeClock, MemoryCacheStore, MemoryUsageStore

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "epss" / "epss_scores.csv"
CURSOR = {"score_date": "2026-10-08", "model_version": "v2026.06.15"}


def csv_gz() -> bytes:
    return gzip.compress(FIXTURE.read_bytes())


def test_definition_and_license() -> None:
    assert definition_errors(EpssCollector) == []
    assert EpssCollector.classification is Classification.PUBLIC
    assert EpssCollector.schedule == Cron("30 16 * * *")
    assert EpssCollector.license.commercial_use == "yes"
    assert EpssCollector.license.attribution == (
        "EPSS scores from FIRST.org (https://www.first.org/epss), generated by Empirical Security."
    )
    # No API key: the collector is never disabled for a missing setting.
    assert EpssCollector.required_settings == ()
    assert EpssCollector.optional_settings == ()


def test_parse_header() -> None:
    header = parse_header("#model_version:v2026.06.15,score_date:2026-10-08T12:00:21Z\n")

    assert header == {"model_version": "v2026.06.15", "score_date": "2026-10-08T12:00:21Z"}


@pytest.mark.parametrize("line", ["cve,epss,percentile", "#model_version:v1", "#score_date:x"])
def test_parse_header_rejects_missing_fields(line: str) -> None:
    with pytest.raises(ValueError):
        parse_header(line)


def test_normalize() -> None:
    raw = {
        "cve": "CVE-2021-44228",
        "epss": "0.99999",
        "percentile": "1.0",
        "model_version": "v2026.06.15",
        "score_date": "2026-10-08T12:00:21Z",
    }

    [entity] = EpssCollector().normalize(raw)

    assert entity == EpssScore(
        cve_id="CVE-2021-44228",
        epss=0.99999,
        percentile=1.0,
        model_version="v2026.06.15",
        score_date=date(2026, 10, 8),
    )


def test_normalize_rejects_invalid_values() -> None:
    raw = {
        "cve": "CVE-X",
        "epss": "2",
        "percentile": "0.1",
        "model_version": "v",
        "score_date": "2026-10-08",
    }

    with pytest.raises(ValueError):
        list(EpssCollector().normalize(raw))


def score(epss: float, model_version: str = "v2026.06.15") -> EpssScore:
    return EpssScore(
        cve_id="CVE-2026-0001",
        epss=epss,
        percentile=0.5,
        model_version=model_version,
        score_date=date(2026, 10, 9),
    )


def stored(epss: float, history_epss: float | None = None) -> StoredScore:
    return StoredScore(
        epss=epss,
        percentile=0.5,
        model_version="v2026.06.15",
        history_epss=epss if history_epss is None else history_epss,
    )


@pytest.mark.parametrize(
    ("previous", "new", "expected"),
    [
        (None, score(0.1), "first"),
        (stored(0.1), score(0.1, model_version="v2027.01.01"), "model"),
        (stored(0.495), score(0.502), "threshold"),
        (stored(0.502), score(0.495), "threshold"),
        (stored(0.02), score(0.03), "change"),
        (stored(0.20), score(0.195), None),
        # Slow drift: each step is small, the total since the last entry is not.
        (stored(0.025, history_epss=0.02), score(0.03), "change"),
        (stored(0.025, history_epss=0.02), score(0.029), None),
    ],
)
def test_history_reason(previous: StoredScore | None, new: EpssScore, expected: str | None) -> None:
    assert history_reason(previous, new, threshold=0.5) == expected


@pytest.fixture
async def http() -> AsyncIterator[SourceHttpClient]:
    clock = FakeClock()
    async with httpx.AsyncClient() as client:
        yield SourceHttpClient(
            source="epss",
            client=client,
            cache=MemoryCacheStore(),
            usage=MemoryUsageStore(),
            cache_ttl=timedelta(hours=12),
            classification=Classification.PUBLIC,
            now=clock.now,
            monotonic=clock.monotonic,
            sleep=clock.sleep,
        )


async def collect(
    http: SourceHttpClient, cursor: Cursor | None, *, full: bool = False
) -> tuple[list[RawRecord], Cursor | None]:
    collector = EpssCollector()
    ctx = CollectorContext(
        http=http, cursor=cursor, secrets={}, logger=logging.getLogger("t"), full=full
    )
    records = [record async for record in collector.fetch(ctx)]
    return records, collector.next_cursor(ctx)


@pytest.mark.anyio
async def test_fetch_reads_gzipped_csv(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(return_value=httpx.Response(200, content=csv_gz()))

    records, cursor = await collect(http, None)

    assert [record["cve"] for record in records] == [
        "CVE-1999-0001",
        "CVE-1999-0002",
        "CVE-2021-44228",
        "CVE-2026-59310",
        "CVE-2026-88779",
    ]
    assert records[0]["model_version"] == "v2026.06.15"
    assert cursor == CURSOR


@pytest.mark.anyio
async def test_fetch_accepts_already_decoded_body(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(return_value=httpx.Response(200, content=FIXTURE.read_bytes()))

    records, _cursor = await collect(http, None)

    assert len(records) == 5


@pytest.mark.anyio
async def test_same_score_date_is_skipped(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(return_value=httpx.Response(200, content=csv_gz()))

    records, cursor = await collect(http, dict(CURSOR))

    assert records == []
    assert cursor == CURSOR


@pytest.mark.anyio
async def test_new_score_date_is_processed(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(return_value=httpx.Response(200, content=csv_gz()))

    records, cursor = await collect(http, {**CURSOR, "score_date": "2026-10-07"})

    assert len(records) == 5
    assert cursor == CURSOR


@pytest.mark.anyio
async def test_full_flag_ignores_cursor(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(return_value=httpx.Response(200, content=csv_gz()))

    records, _cursor = await collect(http, dict(CURSOR), full=True)

    assert len(records) == 5


@pytest.mark.anyio
async def test_unexpected_format_fails(
    respx_mock: respx.MockRouter, http: SourceHttpClient
) -> None:
    respx_mock.get(FEED_URL).mock(
        return_value=httpx.Response(200, content=b"#model_version:v1,score_date:2026-10-08\na,b\n")
    )

    with pytest.raises(ValueError, match="unexpected EPSS CSV columns"):
        await collect(http, None)
