"""Local users and sessions (docs/architettura.md §10.4).

Operational tables, like the collector ones: they hold no intelligence data and
have no classification column.
"""

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

ROLES = ("viewer", "analyst", "admin")


class UserRow(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    # Stored lower-case; the login compares lower-case too.
    email: Mapped[str] = mapped_column(String(254), unique=True)
    # argon2id hash (PHC string), never the password.
    password_hash: Mapped[str] = mapped_column(Text)
    role: Mapped[str] = mapped_column(String(16))
    is_active: Mapped[bool] = mapped_column(Boolean, server_default="true")
    # Set when an Admin chooses the password: the user must change it at first login.
    must_change_password: Mapped[bool] = mapped_column(Boolean, server_default="false")
    failed_logins: Mapped[int] = mapped_column(Integer, server_default="0")
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Second factor (Admins): secrets encrypted with app.services.secretbox.
    totp_enabled: Mapped[bool] = mapped_column(Boolean, server_default="false")
    totp_secret: Mapped[str | None] = mapped_column(Text)
    # Generated by /auth/totp/setup, becomes totp_secret once a code confirms it.
    totp_pending_secret: Mapped[str | None] = mapped_column(Text)
    # Last accepted time step: a code is never accepted twice.
    totp_last_step: Mapped[int | None] = mapped_column(BigInteger)
    password_changed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        CheckConstraint("role IN ('viewer', 'analyst', 'admin')", name="role"),
        CheckConstraint("email = lower(email)", name="email_lower"),
    )


class SessionRow(Base):
    __tablename__ = "sessions"

    # SHA-256 of the cookie token: a database leak does not give usable sessions.
    token_hash: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    csrf_token: Mapped[str] = mapped_column(String(64))
    # Password checked, second factor still missing: gives access to the TOTP endpoints only.
    mfa_pending: Mapped[bool] = mapped_column(Boolean, server_default="false")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    # Absolute end of the session (created_at + 10 hours).
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    ip: Mapped[str | None] = mapped_column(String(45))
    user_agent: Mapped[str | None] = mapped_column(String(255))


class RecoveryCodeRow(Base):
    """One-time recovery codes of the second factor, stored as SHA-256 only."""

    __tablename__ = "user_recovery_codes"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    code_hash: Mapped[str] = mapped_column(String(64))
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (UniqueConstraint("user_id", "code_hash"),)


class LoginFailureRow(Base):
    """Failed login attempts per client IP, for the per-IP limit."""

    __tablename__ = "login_failures"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ip: Mapped[str] = mapped_column(String(45))
    attempted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
