"""EPSS - Exploit Prediction Scoring System (docs/architettura.md §6.1, §6.2, §8.1).

The scores of all CVEs are published once a day as a gzipped CSV (~385,000
rows). Its first line is a comment with the model version and the score date:

    #model_version:v2026.06.15,score_date:2026-10-08T12:00:21Z
    cve,epss,percentile

A run whose score date and model version were already processed reads nothing.
`epss_scores` keeps the current values; `epss_history` keeps only the relevant
changes (first appearance, model change, threshold crossing, change of at
least 0.01 since the last history entry).

Verified on 2026-10-08 against https://www.first.org/epss/data_stats and the
FIRST EPSS FAQ (free use, attribution requested). The FIRST API is meant for
point lookups and is not used for the daily sync.
"""

import csv
import gzip
import io
from collections.abc import AsyncIterator, Iterable, Sequence
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.collectors.base import (
    CollectorContext,
    Cron,
    Cursor,
    PeriodicCollector,
    RawRecord,
    Schedule,
    SourceLicense,
)
from app.collectors.registry import register
from app.collectors.writers import WriteStats, register_writer
from app.core.classification import Classification
from app.core.config import get_settings
from app.models import EpssHistoryRow, EpssScoreRow

FEED_URL = "https://epss.empiricalsecurity.com/epss_scores-current.csv.gz"
GZIP_MAGIC = b"\x1f\x8b"
# A change smaller than this is not kept in the history (scores have 5 decimals).
HISTORY_MIN_CHANGE = 0.01


class EpssScore(BaseModel):
    model_config = ConfigDict(frozen=True)

    cve_id: str = Field(pattern=r"^CVE-[0-9]{4}-[0-9]{4,19}$")
    epss: float = Field(ge=0, le=1)
    percentile: float = Field(ge=0, le=1)
    model_version: str = Field(min_length=1, max_length=32)
    score_date: date


def parse_header(line: str) -> dict[str, str]:
    """`#model_version:v2026.06.15,score_date:2026-10-08T12:00:21Z` -> dict."""
    if not line.startswith("#"):
        raise ValueError("EPSS file without the model/date comment line")
    fields: dict[str, str] = {}
    for part in line[1:].strip().split(","):
        key, separator, value = part.partition(":")
        if separator:
            fields[key.strip()] = value.strip()
    if not fields.get("model_version") or not fields.get("score_date"):
        raise ValueError("EPSS comment line without model_version or score_date")
    return fields


def parse_score_date(value: str) -> date:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).date()


@dataclass(frozen=True)
class StoredScore:
    """Current values of a CVE in `epss_scores`."""

    epss: float
    percentile: float
    model_version: str
    history_epss: float


def history_reason(previous: StoredScore | None, score: EpssScore, threshold: float) -> str | None:
    """Why `score` goes in the history, or None when the change is not relevant."""
    if previous is None:
        return "first"
    if previous.model_version != score.model_version:
        return "model"
    if (previous.epss >= threshold) != (score.epss >= threshold):
        return "threshold"
    # Rounded to the published precision: 0.03 - 0.02 must count as 0.01.
    if round(abs(score.epss - previous.history_epss), 5) >= HISTORY_MIN_CHANGE:
        return "change"
    return None


@register
class EpssCollector(PeriodicCollector):
    name = "epss"
    display_name = "EPSS - Exploit Prediction Scoring System"
    classification = Classification.PUBLIC
    license = SourceLicense(
        kind="Free use with attribution (FIRST EPSS FAQ)",
        commercial_use="yes",
        terms_url="https://www.first.org/epss/faq",
        quota=None,
        attribution=(
            "EPSS scores from FIRST.org (https://www.first.org/epss), "
            "generated by Empirical Security."
        ),
        notes="No formal license: the FAQ allows free use and asks for attribution in products.",
        verified_on=date(2026, 10, 8),
    )
    # Published around 13:30 UTC; 16:30 Europe/Rome leaves a margin all year.
    schedule: ClassVar[Schedule] = Cron("30 16 * * *")
    cache_ttl = timedelta(hours=12)

    def __init__(self) -> None:
        self._header: dict[str, str] | None = None

    async def fetch(self, ctx: CollectorContext) -> AsyncIterator[RawRecord]:
        response = await ctx.http.get(FEED_URL)
        body = response.content
        # httpx already decodes a `Content-Encoding: gzip` response.
        if body.startswith(GZIP_MAGIC):
            body = gzip.decompress(body)
        lines = io.StringIO(body.decode("utf-8"))
        header = parse_header(lines.readline())
        self._header = header
        if not ctx.full and ctx.cursor and self._cursor_value(header) == ctx.cursor:
            ctx.logger.info("EPSS scores of %s already processed", header["score_date"])
            return
        reader = csv.DictReader(lines)
        if reader.fieldnames is None or not {"cve", "epss", "percentile"} <= set(reader.fieldnames):
            raise ValueError("unexpected EPSS CSV columns")
        for row in reader:
            yield {
                **row,
                "model_version": header["model_version"],
                "score_date": header["score_date"],
            }

    def normalize(self, raw: RawRecord) -> Iterable[BaseModel]:
        return [
            EpssScore(
                cve_id=str(raw["cve"]).strip(),
                epss=float(raw["epss"]),
                percentile=float(raw["percentile"]),
                model_version=str(raw["model_version"]),
                score_date=parse_score_date(str(raw["score_date"])),
            )
        ]

    @staticmethod
    def _cursor_value(header: dict[str, str]) -> Cursor:
        return {
            "score_date": parse_score_date(header["score_date"]).isoformat(),
            "model_version": header["model_version"],
        }

    def next_cursor(self, ctx: CollectorContext) -> Cursor | None:
        if self._header is None:
            return ctx.cursor
        return self._cursor_value(self._header)


@register_writer(EpssScore)
async def write_epss_scores(
    session: AsyncSession, entities: Sequence[BaseModel], classification: Classification
) -> WriteStats:
    """Upsert the changed scores and append the relevant changes to the history."""
    by_cve: dict[str, EpssScore] = {}
    for entity in entities:
        if not isinstance(entity, EpssScore):
            raise TypeError(f"expected EpssScore, got {type(entity).__name__}")
        by_cve[entity.cve_id] = entity
    if not by_cve:
        return WriteStats()

    threshold = get_settings().epss_threshold
    current = await session.execute(
        select(
            EpssScoreRow.cve_id,
            EpssScoreRow.epss,
            EpssScoreRow.percentile,
            EpssScoreRow.model_version,
            EpssScoreRow.history_epss,
        ).where(EpssScoreRow.cve_id.in_(list(by_cve)))
    )
    existing = {
        row.cve_id: StoredScore(row.epss, row.percentile, row.model_version, row.history_epss)
        for row in current
    }
    scores: list[dict[str, Any]] = []
    history: list[dict[str, Any]] = []
    inserted = 0
    for score in by_cve.values():
        previous = existing.get(score.cve_id)
        if (
            previous is not None
            and previous.epss == score.epss
            and previous.percentile == score.percentile
            and previous.model_version == score.model_version
        ):
            continue
        reason = history_reason(previous, score, threshold)
        if previous is None:
            inserted += 1
        if reason is not None:
            history.append(
                {
                    "cve_id": score.cve_id,
                    "score_date": score.score_date,
                    "epss": score.epss,
                    "percentile": score.percentile,
                    "model_version": score.model_version,
                    "reason": reason,
                    "classification": classification,
                }
            )
        scores.append(
            {
                "cve_id": score.cve_id,
                "epss": score.epss,
                "percentile": score.percentile,
                "model_version": score.model_version,
                "score_date": score.score_date,
                # Changes are measured from the last history entry, so slow drifts count too.
                "history_epss": (
                    score.epss if reason is not None or previous is None else previous.history_epss
                ),
                "classification": classification,
            }
        )
    if scores:
        statement = insert(EpssScoreRow).values(scores)
        await session.execute(
            statement.on_conflict_do_update(
                index_elements=[EpssScoreRow.cve_id],
                set_={
                    **{name: statement.excluded[name] for name in scores[0] if name != "cve_id"},
                    "updated_at": func.now(),
                },
            )
        )
    if history:
        await session.execute(insert(EpssHistoryRow).values(history).on_conflict_do_nothing())
    return WriteStats(inserted=inserted, updated=len(scores) - inserted)
